# Generated by Django 5.1.6 on 2025-02-26 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customuser_is_mosque_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Sms',
        ),
        migrations.AddField(
            model_name='distribution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-26 14:32:45+00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='needy',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-02-26 14:32:45+00:00'),
            preserve_default=False,
        ),
    ]
