# Generated by Django 5.1.6 on 2025-02-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='content',
            new_name='message',
        ),
    ]
