# Generated by Django 5.1.6 on 2025-02-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_content_notification_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needy',
            name='status',
        ),
        migrations.AlterField(
            model_name='ressourcetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
