# Generated by Django 5.1.6 on 2025-02-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_notification_user_notification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='users',
        ),
    ]
