# Generated by Django 5.1.6 on 2025-03-01 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_user_notification_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='distribution',
            name='finishe_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distribution',
            name='purpose',
            field=models.CharField(default='', max_length=255),
        ),
    ]
