# Generated by Django 5.1.6 on 2025-03-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_created_at_distribution_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='marial_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widow', 'Widow')], default='single', max_length=255),
        ),
        migrations.AddField(
            model_name='needy',
            name='number_ccp',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='needy',
            name='number_of_children',
            field=models.IntegerField(default=0),
        ),
    ]
