# Generated by Django 5.1.6 on 2025-03-07 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_needy_marial_status_needy_number_ccp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distribution',
            old_name='finishe_time',
            new_name='finish_time',
        ),
    ]
