# Generated by Django 5.1.6 on 2025-03-08 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_finishe_time_distribution_finish_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='distribution',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RemoveField(
            model_name='needy',
            name='documents',
        ),
        migrations.AddField(
            model_name='needy',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='needies', to='core.document'),
        ),
    ]
