# Generated by Django 5.1.6 on 2025-06-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_document_alter_distribution_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribution',
            name='purpose',
        ),
        migrations.AddField(
            model_name='distribution',
            name='percentage',
            field=models.SmallIntegerField(choices=[(0, 0), (33, 33), (66, 66), (100, 100)], default=0),
        ),
        migrations.AddField(
            model_name='needy',
            name='sex',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='needy',
            name='social_status',
            field=models.CharField(choices=[('unemployed', 'عاطل عن العمل'), ('student', 'طالب'), ('retired', 'متقاعد'), ('disabled', 'معاق'), ('employed', 'موظف'), ('self-employed', 'عامل حر'), ('other', 'أخرى')], default='unemployed', max_length=255),
        ),
        migrations.AddField(
            model_name='ressourcetype',
            name='unit',
            field=models.CharField(choices=[('kg', 'كيلوغرام'), ('liter', 'لتر'), ('piece', 'قطعة'), ('box', 'صندوق'), ('DZD', 'دينار جزائري')], default='kg', max_length=50),
        ),
        migrations.AlterField(
            model_name='needy',
            name='marial_status',
            field=models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widow', 'أرمل')], default='single', max_length=255),
        ),
    ]
