# Generated by Django 5.1.6 on 2025-06-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_distribution_purpose_distribution_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='sex',
            field=models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ressourcetype',
            name='unit',
            field=models.CharField(choices=[('kg', 'كيلوغرام'), ('liter', 'لتر'), ('piece', 'قطعة'), ('box', 'صندوق'), ('DZD', 'دينار جزائري')], max_length=50),
        ),
    ]
