# Generated by Django 5.1.6 on 2025-06-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_needy_sex_alter_ressourcetype_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='needy',
            name='distributions',
            field=models.ManyToManyField(related_name='enrolled_needy', to='core.distribution'),
        ),
    ]
