# Generated by Django 5.1.6 on 2025-06-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_needy_distributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='distributions',
            field=models.ManyToManyField(blank=True, null=True, related_name='enrolled_needy', to='core.distribution'),
        ),
    ]
