# Generated by Django 5.1.6 on 2025-07-14 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_needy_distributions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='needy',
            name='distributions',
            field=models.ManyToManyField(related_name='enrolled_needy', to='core.distribution'),
        ),
        migrations.AlterField(
            model_name='needy',
            name='number_ccp',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
